### ISSUE TITLE
 generator' object has no attribute 

### ISSUE THREAD

**Issue by PotatoThanh** [balakg/voxelmorph#3]
When I ran the code with tensorflow 1.6 and cuda 9.0, I got this error:
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train(**vars(args))
  File "train.py", line 73, in train
    X = train_example_gen.__next__()[0]
AttributeError: 'generator' object has no attribute '__next__'

**Comment by JJGO** [comment]
I believe this is because you run that with Python 3 whereas the code currently requires Python 2.7. The generator API changed from Python 2 to Python 3 (see [here](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-next-function-and-next-method)). We will provide a Python 3 compatible version in the near future.

**Comment by adalca** [comment]
To tack on @JJGO's answer, I believe that line in train.py now reads:
`X = train_example_gen.__next__()[0]`
which should be compatible with Python 3.
Perhaps you did not have the latest version?
